---
- hosts: localhost
  become: true
  gather_facts: false
  tasks:
    - name: Update yum packages
      yum:
        name: "*"
        state: latest
      vars:
        ansible_pkg_mgr: yum

    - name: Add Jenkins to repo
      get_url:
        url: https://pkg.jenkins.io/redhat-stable/jenkins.repo
        dest: /etc/yum.repos.d/jenkins.repo

    - name: Download Jenkins key
      shell: sudo rpm --import https://pkg.jenkins.io/redhat-stable/jenkins.io.key

    - name: Install JDK
      yum:
        name: java-11-openjdk
        state: present

    - name: Install Jenkins
      yum:
        name: jenkins
        state: present

    - name: Upgrade yum
      shell: yum upgrade -y

    - name: Install Docker and yum-utils
      yum:
        name: ['docker', 'yum-utils']
        state: present

    - name: Enable Jenkins service
      service:
        name: jenkins
        state: started

    - name: Add Jenkins to sudoers
      lineinfile:
        path: /etc/sudoers.d/90-cloud-init-users
        line: "jenkins ALL=(ALL) NOPASSWD:ALL"

    - name: Copy sudo file back
      command: cp /tmp/90-cloud-init-users /etc/sudoers.d/90-cloud-init-users

    - name: Copy Jenkins password file
      command: sudo cat /var/lib/jenkins/secrets/initialAdminPassword > /home/ec2-user/Jpassword.txt

    - name: Add Jenkins user to Docker group
      user:
        name: jenkins
        groups: docker
        append: yes

    - name: Restart Jenkins service
      service:
        name: jenkins
        state: restarted
